inherit_from: .rubocop_todo.yml

# rspec expect{...} is conventional
Style/SpaceBeforeBlockBraces:
  Exclude:
    - 'spec/**/*_spec.rb'

# Allow for alignment
Style/SpaceAroundOperators:
  MultiSpaceAllowedForOperators: true

Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 200
